# Math Primer for AI

본 페이지는 한림대학교 인공지능개론(717005) 수업에서 학생들의 Python 학습을 위해 만든 페이지입니다.

In [1]:
import numpy as np

## Matrix multiplication

In [2]:
a = np.array([[1, -3, 2], [4, 0, -5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [3]:
a.shape

(2, 3)

In [4]:
b = np.array([[3], [1], [2]])
print(b)

[[3]
 [1]
 [2]]


In [5]:
c = np.matmul(a, b)
print(c)

[[4]
 [2]]


In [6]:
d = np.dot(a, b)
print(d)

[[4]
 [2]]


위 둘의 결과 (matmul, dot) 가 어떤가요? 확인해보세요

In [7]:
d.shape

(2, 1)